trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'ServiceConnectionName1'
  resourceGroupName: 'Akhil_Test'
  location: 'East US'

jobs:
- job: DeployVNet
  displayName: 'Deploy VNet'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: AzureResourceGroupDeployment@3
    inputs:
      azureSubscription: $(azureSubscription)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/_Your-Linked-Artifact-Name_/your-vnet-arm-template.json'
      overrideParameters: '-vnetName $(vnetName) -vnetAddressPrefix $(vnetAddressPrefix) -subnet1Name $(subnet1Name) -subnet1Prefix $(subnet1Prefix) -subnet2Name $(subnet2Name) -subnet2Prefix $(subnet2Prefix) -location $(location)'
