trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'ServiceConnectionName1'
  resourceGroupName: 'Akhil_Test'
  location: 'East US'
  vnetName: 'VNet1'
  vnetAddressPrefix: '10.0.0.0/16'
  subnet1Name: 'Subnet1'
  subnet1Prefix: '10.0.0.0/24'
  subnet2Name: 'Subnet2'
  subnet2Prefix: '10.0.1.0/24'

jobs:
- job: DeployVNet
  displayName: 'Deploy VNet'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: AzureResourceGroupDeployment@3
    inputs:
      ConnectedServiceName: $(azureSubscription)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      templateLocation: 'URL of the file'
      csmFile: 'https://raw.githubusercontent.com/neelaakhil97/rep1/main/VNET.json'
      overrideParameters: '-vnetName $(vnetName) -vnetAddressPrefix $(vnetAddressPrefix) -subnet1Name $(subnet1Name) -subnet1Prefix $(subnet1Prefix) -subnet2Name $(subnet2Name) -subnet2Prefix $(subnet2Prefix) -location $(location)'
